name: "Setup Node/Bun Environment"
description: "Common setup steps: checkout, bun, cache, install, and optionally Playwright"

inputs:
  playwright:
    description: "Install Playwright browsers"
    required: false
    default: "false"
  bun-version:
    description: "Bun version to use"
    required: false
    default: "1.3.5"

  bun-version-file:
    description: "Path to file containing Bun version"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          ~/.bun/install/state
          node_modules
        key: ${{ runner.os }}-bun-${{ inputs.bun-version }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ inputs.bun-version }}-
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Cache Playwright browsers
      if: inputs.playwright == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      if: inputs.playwright == 'true'
      shell: bash
      run: bun run test:e2e:install
