# Cloudflare Pages Wrangler設定
name = "kazkiueda-com"
compatibility_date = "2023-12-01"

# Cloudflare Pagesの基本設定
[site]
bucket = "./dist"

# Cloudflare Pagesのビルド設定
[build]
command = "npm run build"

# 環境変数の設定例（Cloudflare Dashboardでも設定可能）
[vars]
# EXAMPLE_VAR = "example-value"

# KV Namespaceの例
# [kv_namespaces]
# MY_KV = { binding = "MY_KV", id = "your-kv-id-here" }

# D1 Databaseの例
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id-here"
