name: Quality Assurance

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # 1. リンティングとフォーマット（最初に実行）
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Run linting and formatting checks
        run: bun run check

  # 2. セキュリティと依存関係チェック（lintと並列実行可能）
  security:
    name: Security & Dependency Check
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Run security audit
        run: bun audit

  # 3. 包括的コード分析（lintと並列実行可能）
  code-analysis:
    name: Comprehensive Code Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 6
    if: |
      github.event_name == 'pull_request' ||
      contains(github.event.head_commit.modified, 'src/') ||
      contains(github.event.head_commit.added, 'src/') ||
      contains(github.event.head_commit.modified, 'package.json') ||
      contains(github.event.head_commit.modified, 'bun.lockb')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Cache Graphviz
        id: cache-graphviz
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/dot
            /usr/bin/dot
          key: ${{ runner.os }}-graphviz-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-graphviz-

      - name: Install Graphviz for Madge
        if: steps.cache-graphviz.outputs.cache-hit != 'true'
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            brew install graphviz
          elif [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y graphviz
          elif [ "$RUNNER_OS" = "Windows" ]; then
            choco install graphviz
          fi
        shell: bash

      - name: Run critical code analysis
        run: |
          echo "Running critical code analysis..."
          echo "1. Checking for unused code and dependencies..."
          bun run analyze:unused
        shell: bash

      - name: Run optional code analysis
        run: |
          echo "Running optional code analysis..."
          echo "2. Checking for circular dependencies..."
          bun run analyze:circular || echo "Circular dependency check completed..."
          echo "3. Checking for orphan modules..."
          bun run analyze:orphans || echo "Orphan modules check completed..."
          echo "4. Checking for leaf modules..."
          bun run analyze:leaves || echo "Leaf modules check completed..."
        shell: bash
        continue-on-error: true

      - name: Generate detailed reports
        run: |
          echo "Generating detailed analysis reports..."
          bun run analyze:unused:reports || echo "Report generation failed but continuing..."
        shell: bash
        continue-on-error: true

      - name: Upload analysis reports as artifacts
        uses: actions/upload-artifact@v4
        if: |
          always() && 
          (github.event_name == 'pull_request' || 
           contains(github.event.head_commit.modified, 'src/'))
        with:
          name: code-analysis-reports-${{ github.job }}-${{ github.run_id }}
          path: |
            knip.json
            circular-dependencies.svg
            dependency-graph.gv
          retention-days: 7

  # 4. ビルド（lintと並列実行可能）
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Build application
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  # 5. ユニットテスト（lintと並列実行可能）
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Run unit tests
        run: bun run test

  # 6. カバレッジテスト（lintと並列実行可能）
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Run test coverage
        run: bun run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  # 7. E2Eテスト（全ての前段階テスト成功後）
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build, unit-tests, coverage, code-analysis]
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun with Cache
        uses: ./.github/actions/setup-bun

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/bun.lockb', '**/playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Setup Playwright
        run: bunx playwright install --with-deps

      - name: Run E2E tests
        run: bun run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7 